#!/usr/bin/env python

import sys
import os
from ase import Atoms
from ase.io import read, write
from ase.io.vasp import write_vasp

def main():
    arg = sys.argv
    inputfile = arg[2]
    cwd = os.getcwd()
    job_name = cwd.split('/')
    outputfile = job_name[len(job_name)-1]+'.xyz'
    cmd_para = ['tail -n', str(arg[1]), inputfile, '>', outputfile]
    join_symbol = ' '
    cmd = join_symbol.join(cmd_para)
    os.system(cmd)
    print(cmd)
if __name__ == '__main__':
    main()
    
